[package]
name = "voxel-tile-raycast"
version = "0.1.0"
edition = "2021"
description = "Ray casting for voxel and tile maps"
license = "MIT"

[dependencies]
nalgebra = "0.32"

[features]
default = ["f64", "tile", "voxel"]
f64 = []
f32 = []
tile = []
voxel = []